spring:
  application:
    name: st-microservice-ili
  servlet:
    multipart:
      maxFileSize: 250MB
      maxRequestSize: 250MB

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 9005
  tomcat:
    max-threads: 0

      